### ISSUE TITLE
Translation policy

### ISSUE THREAD

**Issue by noolbar** [aratama/purescript-book-ja#2]
Thank you for keeping updating.
I am very happy to see that my uncommon Japanese being brushed up.

When I translated, I made some changes not in the original books.
I do not remember all, but I hope that it will be helpful for translations.
So I write the following together with typo I found.

src/chapter03.md line 30
 add below
 [+] ダブルドット(..)を使用すると、指定された型コンストラクタのすべてのデータコンストラクタをインポートできます。

src/chapter04.md line 45
 spelling of Fibonacci

src/chapter08.md line 594
 rewrite old
 [-] print n
 [+] logShow n

src/chapter11.md line 401
a typographical error
 [-] `lfft`を使えばいつでも
 [+] `lift`を使えばいつでも

**Comment by aratama** [comment]
Thanks for your information. Fixed.
I'll keep your additional explanations as "訳者注" in chapter 03. 
Any suggestions or pull requests are welcome.
